server:
  port: 8182
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sinawo@%__1
  devtools:
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"

#Email settings
  config:
    import: 'optional:secret.yml'
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    smtp:
      ssl:
        trust: smtp.gmail.com
mail:
  transport:
    protocol: smtp

# Application settings
site:
  domain: http://localhost:8182/